export interface Book {
  id: string;
  title: string;
  urduTitle: string;
  year: number | string;
  category: 'book' | 'sharah' | 'paper' | 'entry';
  driveLink: string;
  image?: string;
}

export interface YearData {
  year: number | string;
  name: string;
  urduName: string;
  books: Book[];
  sharahs: Book[];
  papers?: Book[];
}

// Year-wise different images from public/image folder
const YEAR_IMAGES: Record<number, string> = {
  1: '/image/1year.png',
  2: '/image/2year.jpeg',
  3: '/image/3year.jpg',
  4: '/image/4year.jpg',
  5: '/image/5year.jpg',
  6: '/image/6year.webp',
  7: '/image/7year.webp',
  8: '/image/8 year.jpg',
};

const PAPER_IMAGE = 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&h=500&fit=crop';

export const allData: YearData[] = [
  {
    year: 1,
    name: 'Darja Oola (1st Year)',
    urduName: 'درجہ اولیٰ',
    books: [
      { id: '1-1', title: 'Khulasa Tul Nahve Solve', urduTitle: 'خلاصۃ النحو حل شدہ', year: 1, category: 'book', driveLink: '/books/1th year/Khulasa Tul Nahve  Solve.pdf', image: YEAR_IMAGES[1] },
      { id: '1-2', title: 'Nisab Us Sarf', urduTitle: 'نصاب الصرف', year: 1, category: 'book', driveLink: '/books/1th year/nisab-us-sarf.pdf', image: YEAR_IMAGES[1] },
      { id: '1-3', title: 'Taysir Abwabul Sarf', urduTitle: 'تیسیر ابواب الصرف', year: 1, category: 'book', driveLink: '/books/1th year/تیسیر ابواب الصرف.pdf', image: YEAR_IMAGES[1] },
    ],
    sharahs: [],
    papers: [],
  },
  {
    year: 2,
    name: 'Darja Sania (2nd Year)',
    urduName: 'درجہ ثانیہ',
    books: [
      { id: '2-1', title: 'Duroosul Balagha Sharah', urduTitle: 'دروس البلاغۃ شرح', year: 2, category: 'book', driveLink: '/books/2th Year/Duroosul balagha sharah.pdf', image: YEAR_IMAGES[2] },
      { id: '2-2', title: 'Marif Un Nahw', urduTitle: 'معارف النحو', year: 2, category: 'book', driveLink: '/books/2th Year/MARIF-UN-NAHW-URDU-SHARH-HIDAYAT-UN-NAHW.pdf', image: YEAR_IMAGES[2] },
      { id: '2-3', title: 'Miftahul Awamil', urduTitle: 'مفتاح العوامل', year: 2, category: 'book', driveLink: '/books/2th Year/MiftahUlAwamilUrduSharhSharhEMiataAamil.pdf', image: YEAR_IMAGES[2] },
      { id: '2-4', title: 'Qudoori Sharah', urduTitle: 'قدوری شرح', year: 2, category: 'book', driveLink: '/books/2th Year/Qudoori sharah.pdf', image: YEAR_IMAGES[2] },
      { id: '2-5', title: 'Sharah Insha Ul Arbia', urduTitle: 'شرح انشاء العربیۃ', year: 2, category: 'book', driveLink: '/books/2th Year/Sharah Insha Ul Arbia.pdf', image: YEAR_IMAGES[2] },
      { id: '2-6', title: 'Sharah Miati Aamil', urduTitle: 'شرح مائۃ عامل', year: 2, category: 'book', driveLink: '/books/2th Year/sharah-miati-aamil ki sharah.pdf', image: YEAR_IMAGES[2] },
      { id: '2-7', title: 'Sharah Noor Ul Eizah', urduTitle: 'شرح نور الایضاح', year: 2, category: 'book', driveLink: '/books/2th Year/SharhNoorUlEizah.pdf', image: YEAR_IMAGES[2] },
      { id: '2-8', title: 'Al-Naw Al-Sadis Al-Sabi', urduTitle: 'النوع السادس النوع السابع', year: 2, category: 'book', driveLink: '/books/2th Year/النوع السادس النوع السابع  شرح مۂة عامل.pdf', image: YEAR_IMAGES[2] },
      { id: '2-9', title: 'Al-Naw Al-Rabi Al-Khamis', urduTitle: 'النوع الرابع النوع الخامس', year: 2, category: 'book', driveLink: '/books/2th Year/النوع الرابع النوع الخامس النوع السادس النوع السابع  شرح مۂة عامل.pdf', image: YEAR_IMAGES[2] },
      { id: '2-10', title: 'Mukhtasar Sharah Miah Amil', urduTitle: 'مختصر شرح مائة عامل', year: 2, category: 'book', driveLink: '/books/2th Year/مختصر شرح مائة عامل.pdf', image: YEAR_IMAGES[2] },
    ],
    sharahs: [],
    papers: [],
  },
  {
    year: 3,
    name: 'Darja Salisa (3rd Year)',
    urduName: 'درجہ ثالثہ',
    books: [
      { id: '3-1', title: 'Ajwad Ul Hawashi', urduTitle: 'اجود الحواشی', year: 3, category: 'book', driveLink: '/books/3th Year/AjwadUlHawashiUrduSharhUsoolUshShashi.pdf', image: YEAR_IMAGES[3] },
      { id: '3-2', title: 'Ata Aeen Tafseer e Jalalain', urduTitle: 'آئین تفسیر الجلالین', year: 3, category: 'book', driveLink: '/books/3th Year/Ata Aeen Tafseer e Jalalain Jild 1.pdf', image: YEAR_IMAGES[3] },
      { id: '3-3', title: 'Tohfatul Mirqat', urduTitle: 'تحفۃ المرقاۃ', year: 3, category: 'book', driveLink: '/books/3th Year/Tohfatul Mirqat.pdf', image: YEAR_IMAGES[3] },
      { id: '3-4', title: 'Tohfatul Balagha', urduTitle: 'تحفۃ البلاغۃ', year: 3, category: 'book', driveLink: '/books/3th Year/TohfatUlBalaghaUrduSharhDuroosUlBalagha.pdf', image: YEAR_IMAGES[3] },
      { id: '3-5', title: 'Usool Shashi Notes', urduTitle: 'اصول الشاشی نوٹس', year: 3, category: 'book', driveLink: '/books/3th Year/اصول الشاشی نوٹس.pdf', image: YEAR_IMAGES[3] },
    ],
    sharahs: [],
    papers: [],
  },
  {
    year: 4,
    name: 'Darja Rabia (4th Year)',
    urduName: 'درجہ رابعہ',
    books: [
      { id: '4-1', title: 'Al Duroos Ul Wafia', urduTitle: 'الدروس الوافیۃ', year: 4, category: 'book', driveLink: '/books/4th Year/AlDuroosUlWafiaUrduSharhKafia.pdf', image: YEAR_IMAGES[4] },
      { id: '4-2', title: 'Khulas E Qutbi', urduTitle: 'خلاصۃ القطبی', year: 4, category: 'book', driveLink: '/books/4th Year/KHULAS_E_QUTBI.pdf', image: YEAR_IMAGES[4] },
      { id: '4-3', title: 'Noor Ul Anwaar Vol 1', urduTitle: 'نور الانوار جلد اول', year: 4, category: 'book', driveLink: '/books/4th Year/NOOR UL ANWAAR VOL 1 AL BUSHRA.pdf', image: YEAR_IMAGES[4] },
      { id: '4-4', title: 'Sharah Shamail e Tirmizi', urduTitle: 'شرح شمائل ترمذی', year: 4, category: 'book', driveLink: '/books/4th Year/Sharah Shamail e Tirmizi.pdf', image: YEAR_IMAGES[4] },
      { id: '4-5', title: 'Tasheel E Qutbi', urduTitle: 'تسہیل القطبی', year: 4, category: 'book', driveLink: '/books/4th Year/TasheelEQutbiUrduSharhAlQutbi.pdf', image: YEAR_IMAGES[4] },
      { id: '4-6', title: 'Tasheel Ul Haqaiq', urduTitle: 'تسہیل الحقائق', year: 4, category: 'book', driveLink: '/books/4th Year/TasheelUlHaqaiqUrduSharhKanzUdDaqaiq1.pdf', image: YEAR_IMAGES[4] },
      { id: '4-7', title: 'Zubda Tul Itqan', urduTitle: 'زبدۃالاتقان فی علوم القرآن', year: 4, category: 'book', driveLink: '/books/4th Year/Zubda tul itqan fi ulloom ul Quran by dr syed muhammad alavi  maliki r.a. زبدۃالاتقان فی علوم القرآن.pdf', image: YEAR_IMAGES[4] },
      { id: '4-8', title: 'Qutbi Notes Jamia Madinah', urduTitle: 'قطبی نوٹس جامعۃ المدینہ', year: 4, category: 'book', driveLink: '/books/4th Year/قطبی نوٹس جامعۃ المدینہ فیضان ابن مسعود.pdf', image: YEAR_IMAGES[4] },
      { id: '4-9', title: 'Kanz Ul Daqaiq Questions', urduTitle: 'کنز الدقائق سوالات', year: 4, category: 'book', driveLink: '/books/4th Year/کنز_الدقائق_درجہ_رابعہ_سوالات_و_جوابات.pdf', image: YEAR_IMAGES[4] },
    ],
    sharahs: [],
    papers: [],
  },
  {
    year: 5,
    name: 'Darja Khamsa (5th Year)',
    urduName: 'درجہ خامسہ',
    books: [
      { id: '5-1', title: 'Al Faozul Kabeer Notes', urduTitle: 'الفوز الکبیر نوٹس', year: 5, category: 'book', driveLink: '/books/5th Year/Al Faozul Kabeer Notes (page 40).pdf', image: YEAR_IMAGES[5] },
      { id: '5-2', title: 'Al Faozul Kabeer Sharah', urduTitle: 'شرح الفوز الکبیر', year: 5, category: 'book', driveLink: '/books/5th Year/Al Faozul Kabeer sharah.pdf', image: YEAR_IMAGES[5] },
      { id: '5-3', title: 'Al Fawzul Azeem Sharah', urduTitle: 'شرح الفوز العظیم', year: 5, category: 'book', driveLink: '/books/5th Year/Al Fawzul Azeem sharah.pdf', image: YEAR_IMAGES[5] },
      { id: '5-4', title: 'Al Jami MCQs', urduTitle: 'الجامع ایم سی کیوز', year: 5, category: 'book', driveLink: '/books/5th Year/Al Jami    MCQs.pdf', image: YEAR_IMAGES[5] },
      { id: '5-5', title: 'Al Jami Arabic', urduTitle: 'الجامع عربی', year: 5, category: 'book', driveLink: '/books/5th Year/Al Jami arabic.pdf', image: YEAR_IMAGES[5] },
      { id: '5-6', title: 'Fiqhul Seerah Notes', urduTitle: 'فقہ السیرۃ نوٹس', year: 5, category: 'book', driveLink: '/books/5th Year/Fiqhul seesrah Notes.pdf', image: YEAR_IMAGES[5] },
      { id: '5-7', title: 'Fiqhul Seerah Q&A', urduTitle: 'فقہ السیرۃ سوال جواب', year: 5, category: 'book', driveLink: '/books/5th Year/Fiqhul Seerah (Q&A).pdf', image: YEAR_IMAGES[5] },
      { id: '5-8', title: 'Fiqhul Seerah Sharah', urduTitle: 'شرح فقہ السیرۃ', year: 5, category: 'book', driveLink: '/books/5th Year/Fiqhul Seerah Sharah.pdf', image: YEAR_IMAGES[5] },
      { id: '5-9', title: 'Fiqhul Seerah (105)', urduTitle: 'فقہ السیرۃ', year: 5, category: 'book', driveLink: '/books/5th Year/Fiqhul Seerah   (page 105).pdf', image: YEAR_IMAGES[5] },
      { id: '5-10', title: 'Hussami (49 page)', urduTitle: 'الحسامی', year: 5, category: 'book', driveLink: '/books/5th Year/Hussami (49 page).pdf', image: YEAR_IMAGES[5] },
      { id: '5-11', title: 'Hussami (105 page)', urduTitle: 'الحسامی', year: 5, category: 'book', driveLink: '/books/5th Year/Hussami   (page 105).pdf', image: YEAR_IMAGES[5] },
      { id: '5-12', title: 'Hussami (123 page)', urduTitle: 'الحسامی', year: 5, category: 'book', driveLink: '/books/5th Year/Hussami    (page 123).pdf', image: YEAR_IMAGES[5] },
      { id: '5-13', title: 'Hussami (266 page)', urduTitle: 'الحسامی', year: 5, category: 'book', driveLink: '/books/5th Year/Hussami   (page 266).pdf', image: YEAR_IMAGES[5] },
      { id: '5-14', title: 'Hussami Notes', urduTitle: 'حسامی نوٹس', year: 5, category: 'book', driveLink: '/books/5th Year/Hussami  Notes.pdf', image: YEAR_IMAGES[5] },
      { id: '5-15', title: 'Hussami Ki Istilahat', urduTitle: 'حسامی کی اصطلاحات', year: 5, category: 'book', driveLink: '/books/5th Year/Hussami ki Istilahat.pdf', image: YEAR_IMAGES[5] },
      { id: '5-16', title: 'Hussami Sharah', urduTitle: 'حسامی کی شرح', year: 5, category: 'book', driveLink: '/books/5th Year/Hussami ki sharah\'.pdf', image: YEAR_IMAGES[5] },
      { id: '5-17', title: 'Hussami MCQs', urduTitle: 'حسامی ایم سی کیوز', year: 5, category: 'book', driveLink: '/books/5th Year/Hussami MCQs.pdf', image: YEAR_IMAGES[5] },
      { id: '5-18', title: 'Mukhtasar Ul Maani (12 page)', urduTitle: 'مختصر المعانی', year: 5, category: 'book', driveLink: '/books/5th Year/Mukhtasar ul Maani     (page 12).pdf', image: YEAR_IMAGES[5] },
      { id: '5-19', title: 'Mukhtasar Ul Maani (111 page)', urduTitle: 'مختصر المعانی', year: 5, category: 'book', driveLink: '/books/5th Year/Mukhtasar ul Maani (111 page).pdf', image: YEAR_IMAGES[5] },
      { id: '5-20', title: 'Mukhtasar Ul Maani Khulasa', urduTitle: 'مختصر المعانی خلاصہ', year: 5, category: 'book', driveLink: '/books/5th Year/Mukhtasar ul Maani (Khulasa).pdf', image: YEAR_IMAGES[5] },
      { id: '5-21', title: 'Mukhtasar Ul Maani NailUlAmani', urduTitle: 'مختصر المعانی نیل الامانی', year: 5, category: 'book', driveLink: '/books/5th Year/Mukhtasar ul Maani (NailUlAmani).pdf', image: YEAR_IMAGES[5] },
      { id: '5-22', title: 'Mukhtasar Ul Maani Arabic', urduTitle: 'مختصر المعانی عربی', year: 5, category: 'book', driveLink: '/books/5th Year/Mukhtasar ul Maani Arabic.pdf', image: YEAR_IMAGES[5] },
      { id: '5-23', title: 'Mukhtasar Ul Maani MCQs', urduTitle: 'مختصر المعانی ایم سی کیوز', year: 5, category: 'book', driveLink: '/books/5th Year/Mukhtasar ul Maani MCQs.pdf', image: YEAR_IMAGES[5] },
      { id: '5-24', title: 'Qasaide Muntakhaba (32 page)', urduTitle: 'قصائد منتخبہ', year: 5, category: 'book', driveLink: '/books/5th Year/Qasaide Muntakhaba (32 page).pdf', image: YEAR_IMAGES[5] },
      { id: '5-25', title: 'Qasaide Muntakhaba (42 page)', urduTitle: 'قصائد منتخبہ', year: 5, category: 'book', driveLink: '/books/5th Year/Qasaide Muntakhaba (42 page).pdf', image: YEAR_IMAGES[5] },
      { id: '5-26', title: 'Qasaide Muntakhaba (45 page)', urduTitle: 'قصائد منتخبہ', year: 5, category: 'book', driveLink: '/books/5th Year/Qasaide Muntakhaba (45 page).pdf', image: YEAR_IMAGES[5] },
      { id: '5-27', title: 'Sharah Wiqaya (Tasheelul Wiqaya jild 1)', urduTitle: 'شرح الوقایۃ', year: 5, category: 'book', driveLink: '/books/5th Year/Sharah Wiqaya (Tasheelul Wiqaya jild 1).pdf', image: YEAR_IMAGES[5] },
      { id: '5-28', title: 'Sharah Wiqaya Awal (105)', urduTitle: 'شرح الوقایۃ اول', year: 5, category: 'book', driveLink: '/books/5th Year/Sharah Wiqaya Awal  (page 105).pdf', image: YEAR_IMAGES[5] },
      { id: '5-29', title: 'Sharah Wiqaya Awal (14)', urduTitle: 'شرح الوقایۃ', year: 5, category: 'book', driveLink: '/books/5th Year/Sharah Wiqaya Awal  (page 14).pdf', image: YEAR_IMAGES[5] },
      { id: '5-30', title: 'Sharah Wiqaya Kitabul Jihad', urduTitle: 'شرح الوقایۃ کتاب الجہاد', year: 5, category: 'book', driveLink: '/books/5th Year/Sharah Wiqaya Kitabul Jihad.pdf', image: YEAR_IMAGES[5] },
      { id: '5-31', title: 'Sharah Wiqaya Shishmahi Sani', urduTitle: 'شرح الوقایۃ ششماہی ثانی', year: 5, category: 'book', driveLink: '/books/5th Year/Sharah Wiqaya Shishmahi Sani.pdf', image: YEAR_IMAGES[5] },
      { id: '5-32', title: 'Sharah Mustalah Al Hadith', urduTitle: 'شرح مصطلح الحدیث', year: 5, category: 'book', driveLink: '/books/5th Year/Sharah-Mustalih-Al-Hadith.pdf', image: YEAR_IMAGES[5] },
      { id: '5-33', title: 'Taeseer Mustalahul Hadees Sharah', urduTitle: 'تیسیر مصطلح الحدیث شرح', year: 5, category: 'book', driveLink: '/books/5th Year/Taeseer  Mustalahul Hadees Sharah.pdf', image: YEAR_IMAGES[5] },
      { id: '5-34', title: 'Taeseer Mustalahul Hadees (67)', urduTitle: 'تیسیر مصطلح الحدیث', year: 5, category: 'book', driveLink: '/books/5th Year/Taeseer Mustalahul Hadees (67 page).pdf', image: YEAR_IMAGES[5] },
      { id: '5-35', title: 'Taeseer Mustalahul Hadees Map', urduTitle: 'تیسیر مصطلح الحدیث میپ', year: 5, category: 'book', driveLink: '/books/5th Year/Taeseer Mustalahul Hadees Map.pdf', image: YEAR_IMAGES[5] },
      { id: '5-36', title: 'Tafseer Madarikul Tanzeel 1', urduTitle: 'تفسیر مدارک التنزیل', year: 5, category: 'book', driveLink: '/books/5th Year/Tafseer Madarikul Tanzeel 1.pdf', image: YEAR_IMAGES[5] },
      { id: '5-37', title: 'Tafseer Madarikul Tanzeel 2', urduTitle: 'تفسیر مدارک التنزیل', year: 5, category: 'book', driveLink: '/books/5th Year/Tafseer Madarikul Tanzeel 2.pdf', image: YEAR_IMAGES[5] },
      { id: '5-38', title: 'Tafseer Madarikul Tanzeel 3', urduTitle: 'تفسیر مدارک التنزیل', year: 5, category: 'book', driveLink: '/books/5th Year/Tafseer Madarikul Tanzeel 3.pdf', image: YEAR_IMAGES[5] },
      { id: '5-39', title: 'Urdu Notes Sharah Jami', urduTitle: 'اردو نوٹس شرح جامی', year: 5, category: 'book', driveLink: '/books/5th Year/اردو_نوٹس_شرح_جامی.pdf', image: YEAR_IMAGES[5] },
      { id: '5-40', title: 'Islam Qabool Karne Ki Ahmiyat', urduTitle: 'اسلام قبول کرنے کی اہمیت و فضیلت', year: 5, category: 'book', driveLink: '/books/5th Year/اسلام قبول کرنے کی اہمیت و فضیلت.pdf', image: YEAR_IMAGES[5] },
      { id: '5-41', title: 'Aghraz Sharah Jami', urduTitle: 'اغراض شرح جامی', year: 5, category: 'book', driveLink: '/books/5th Year/اغراض شرح جامی.pdf', image: YEAR_IMAGES[5] },
      { id: '5-42', title: 'Halat Musannifeen Khamsa', urduTitle: 'حالات مصنّفین خامسہ', year: 5, category: 'book', driveLink: '/books/5th Year/حالات مصنّفین خامسہ.pdf', image: YEAR_IMAGES[5] },
      { id: '5-43', title: 'Sharah Jami Notes', urduTitle: 'شرح جامی نوٹس', year: 5, category: 'book', driveLink: '/books/5th Year/شرح جامی نوٹس.pdf', image: YEAR_IMAGES[5] },
    ],
    sharahs: [],
    papers: [],
  },
  {
    year: 6,
    name: 'Darja Sadisa (6th Year)',
    urduName: 'درجہ سادسہ',
    books: [
      { id: '6-1', title: 'Al Arabiatu Litalibeen Complete', urduTitle: 'العربیۃ للطالبین مکمل', year: 6, category: 'book', driveLink: '/books/6th Year/Al arabiatu litalibeen Complete.pdf', image: YEAR_IMAGES[6] },
      { id: '6-2', title: 'Al Arabiatu Litalibeen Notes', urduTitle: 'العربیۃ للطالبین نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Al arabiatu litalibeen Notes.pdf', image: YEAR_IMAGES[6] },
      { id: '6-3', title: 'Al Arabiatu Litalibeen', urduTitle: 'العربیۃ للطالبین', year: 6, category: 'book', driveLink: '/books/6th Year/Al arabiatu litalibeen.pdf', image: YEAR_IMAGES[6] },
      { id: '6-4', title: 'Falsafa Notes (47)', urduTitle: 'فلسفہ نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Falsafa Notes  (47).pdf', image: YEAR_IMAGES[6] },
      { id: '6-5', title: 'Falsafa Notes (70)', urduTitle: 'فلسفہ نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Falsafa Notes (70).pdf', image: YEAR_IMAGES[6] },
      { id: '6-6', title: 'Fathul Mannan Sharah', urduTitle: 'فتح المنان شرح', year: 6, category: 'book', driveLink: '/books/6th Year/Fathul Mannan (Sharah).pdf', image: YEAR_IMAGES[6] },
      { id: '6-7', title: 'Fathul Mannan Notes (40)', urduTitle: 'فتح المنان نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Fathul Mannan Notes (40).pdf', image: YEAR_IMAGES[6] },
      { id: '6-8', title: 'Fiqhul Akbar Notes (40)', urduTitle: 'الفقہ الاکبر نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Fiqhul Akbar Notes (40).pdf', image: YEAR_IMAGES[6] },
      { id: '6-9', title: 'Fiqhul Akber Khulasa', urduTitle: 'الفقہ الاکبر خلاصہ', year: 6, category: 'book', driveLink: '/books/6th Year/Fiqhul Akber Khulasa with hashiyah.pdf', image: YEAR_IMAGES[6] },
      { id: '6-10', title: 'Hidaya MCQs', urduTitle: 'الہدایۃ ایم سی کیوز', year: 6, category: 'book', driveLink: '/books/6th Year/Hidaya   MCQs.pdf', image: YEAR_IMAGES[6] },
      { id: '6-11', title: 'Hidaya Shishmahi Awal', urduTitle: 'الہدایۃ ششماہی اول', year: 6, category: 'book', driveLink: '/books/6th Year/Hidaya  Shishmahi Awal Notes (78).pdf', image: YEAR_IMAGES[6] },
      { id: '6-12', title: 'Hidaya Sharah Fiyozatur Razwiya 01', urduTitle: 'شرح الہدایۃ فیوضات رضویہ', year: 6, category: 'book', driveLink: '/books/6th Year/Hidaya (Sharah Fiyozatur razwiya 01).pdf', image: YEAR_IMAGES[6] },
      { id: '6-13', title: 'Hidaya Sharah Fiyozatur Razwiya 02', urduTitle: 'شرح الہدایۃ فیوضات رضویہ', year: 6, category: 'book', driveLink: '/books/6th Year/Hidaya (Sharah Fiyozatur razwiya 02).pdf', image: YEAR_IMAGES[6] },
      { id: '6-14', title: 'Hidaya Sharah Fiyozatur Razwiya 03', urduTitle: 'شرح الہدایۃ فیوضات رضویہ', year: 6, category: 'book', driveLink: '/books/6th Year/Hidaya (Sharah Fiyozatur razwiya 03).pdf', image: YEAR_IMAGES[6] },
      { id: '6-15', title: 'Hidaya Sharah Fiyozatur Razwiya 05', urduTitle: 'شرح الہدایۃ فیوضات رضویہ', year: 6, category: 'book', driveLink: '/books/6th Year/Hidaya (Sharah Fiyozatur razwiya 05).pdf', image: YEAR_IMAGES[6] },
      { id: '6-16', title: 'Hidaya Sharah Fiyozatur Razwiya 06', urduTitle: 'شرح الہدایۃ فیوضات رضویہ', year: 6, category: 'book', driveLink: '/books/6th Year/Hidaya (Sharah Fiyozatur razwiya 06).pdf', image: YEAR_IMAGES[6] },
      { id: '6-17', title: 'Hidaya Sharah Fiyozatur Razwiya 07', urduTitle: 'شرح الہدایۃ فیوضات رضویہ', year: 6, category: 'book', driveLink: '/books/6th Year/Hidaya (Sharah Fiyozatur razwiya 07).pdf', image: YEAR_IMAGES[6] },
      { id: '6-18', title: 'Hidaya Shishmahi Sani', urduTitle: 'الہدایۃ ششماہی ثانی', year: 6, category: 'book', driveLink: '/books/6th Year/Hidaya Shishmahi Sani Notes (51).pdf', image: YEAR_IMAGES[6] },
      { id: '6-19', title: 'Ijabatul Ghoose Book', urduTitle: 'اجابۃ الغوس کتاب', year: 6, category: 'book', driveLink: '/books/6th Year/Ijabatul Ghoose Book.pdf', image: YEAR_IMAGES[6] },
      { id: '6-20', title: 'Ijabatul Ghoose Mcqs', urduTitle: 'اجابۃ الغوس ایم سی کیوز', year: 6, category: 'book', driveLink: '/books/6th Year/Ijabatul Ghoose Mcqs.pdf', image: YEAR_IMAGES[6] },
      { id: '6-21', title: 'Ijabatul Ghoose Notes (29)', urduTitle: 'اجابۃ الغوس نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Ijabatul Ghoose Notes (29).pdf', image: YEAR_IMAGES[6] },
      { id: '6-22', title: 'Minhajul Abideen Notes (86)', urduTitle: 'منہاج العابدین نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Minhajul Abideen Notes (86).pdf', image: YEAR_IMAGES[6] },
      { id: '6-23', title: 'Minhajul Abideen Sharah', urduTitle: 'منہاج العابدین شرح', year: 6, category: 'book', driveLink: '/books/6th Year/Minhajul Abideen Sharah.pdf', image: YEAR_IMAGES[6] },
      { id: '6-24', title: 'Munazra Rashidya Complete', urduTitle: 'مناظرہ رشیدیہ مکمل', year: 6, category: 'book', driveLink: '/books/6th Year/Munazra Rashidya Complete Notes (39).pdf', image: YEAR_IMAGES[6] },
      { id: '6-25', title: 'Munazra Rashidya Notes (52)', urduTitle: 'مناظرہ رشیدیہ نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Munazra Rashidya Notes (52).pdf', image: YEAR_IMAGES[6] },
      { id: '6-26', title: 'Noorul Mubeen Sharah', urduTitle: 'نور المبین شرح', year: 6, category: 'book', driveLink: '/books/6th Year/Noorul Mubeen Sharah.pdf', image: YEAR_IMAGES[6] },
      { id: '6-27', title: 'Norul Mubeen (66)', urduTitle: 'نور المبین', year: 6, category: 'book', driveLink: '/books/6th Year/Norul Mubeen  (66).pdf', image: YEAR_IMAGES[6] },
      { id: '6-28', title: 'Norul Mubeen Notes (52)', urduTitle: 'نور المبین نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Norul Mubeen Notes (52).pdf', image: YEAR_IMAGES[6] },
      { id: '6-29', title: 'Norul Mubeen Notes (53)', urduTitle: 'نور المبین نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Norul Mubeen Notes (53).pdf', image: YEAR_IMAGES[6] },
      { id: '6-30', title: 'Norul Mubeen Notes (65)', urduTitle: 'نور المبین نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Norul Mubeen Notes (65).pdf', image: YEAR_IMAGES[6] },
      { id: '6-31', title: 'Tafseere Bidawi Awal Note (68)', urduTitle: 'تفسیر بیضاوی اول نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Tafseere Bidawi (Awal) Note (68).pdf', image: YEAR_IMAGES[6] },
      { id: '6-32', title: 'Tafseere Bidawi Awal Notes (73)', urduTitle: 'تفسیر بیضاوی اول نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Tafseere Bidawi (Awal) Notes (73).pdf', image: YEAR_IMAGES[6] },
      { id: '6-33', title: 'Tafseere Bidawi Sani Notes (79)', urduTitle: 'تفسیر بیضاوی ثانی نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Tafseere Bidawi (Sani) Notes (79).pdf', image: YEAR_IMAGES[6] },
      { id: '6-34', title: 'Tafseere Bidawi Sharah', urduTitle: 'تفسیر بیضاوی شرح', year: 6, category: 'book', driveLink: '/books/6th Year/Tafseere Bidawi (Sharah).pdf', image: YEAR_IMAGES[6] },
      { id: '6-35', title: 'Tafseere Bidawi Arabic', urduTitle: 'تفسیر بیضاوی عربی', year: 6, category: 'book', driveLink: '/books/6th Year/Tafseere Bidawi Arabic.pdf', image: YEAR_IMAGES[6] },
      { id: '6-36', title: 'Usoolul Dawa Notes (75)', urduTitle: 'اصول الدعۃ نوٹس', year: 6, category: 'book', driveLink: '/books/6th Year/Usoolul Dawa Notes (75).pdf', image: YEAR_IMAGES[6] },
      { id: '6-37', title: 'Usoolul Dawa Tamareen', urduTitle: 'اصول الدعۃ تمرین', year: 6, category: 'book', driveLink: '/books/6th Year/Usoolul Dawa Tamareen.pdf', image: YEAR_IMAGES[6] },
      { id: '6-38', title: 'Talqis Hidayah Kitabul Talaq', urduTitle: 'تلخیص ہدایۃ کتاب الطلاق', year: 6, category: 'book', driveLink: '/books/6th Year/تلخیص_ہدایہ_کتاب_الطلاق_والنکاح_.pdf', image: YEAR_IMAGES[6] },
      { id: '6-39', title: 'Munazra Rashidiya Khulasa', urduTitle: 'مناظرہ رشیدیہ کا خلاصہ', year: 6, category: 'book', driveLink: '/books/6th Year/مناظرہ رشیدیہ کا خلاصہ.pdf', image: YEAR_IMAGES[6] },
      { id: '6-40', title: 'Hidaya Kitabul Taharat', urduTitle: 'الہدایۃ کتاب الطہارت', year: 6, category: 'book', driveLink: '/books/6th Year/ہدایہ کتاب الطھارت اختلافی مسائل.pdf', image: YEAR_IMAGES[6] },
    ],
    sharahs: [],
    papers: [],
  },
  {
    year: 7,
    name: 'Darja Sabia (7th Year)',
    urduName: 'درجہ سابعہ',
    books: [
      { id: '7-1', title: 'Aqaide Nasfiya (150)', urduTitle: 'عقائد نسفیہ', year: 7, category: 'book', driveLink: '/books/7th Year/Aqaide Nasfiya  (150).pdf', image: YEAR_IMAGES[7] },
      { id: '7-2', title: 'Aqaide Nasfiya (34)', urduTitle: 'عقائد نسفیہ', year: 7, category: 'book', driveLink: '/books/7th Year/Aqaide Nasfiya  (34).pdf', image: YEAR_IMAGES[7] },
      { id: '7-3', title: 'Aqaide Nasfiya Awal Saim (56)', urduTitle: 'عقائد نسفیہ اول سائم', year: 7, category: 'book', driveLink: '/books/7th Year/Aqaide Nasfiya Awal Saim  (56).pdf', image: YEAR_IMAGES[7] },
      { id: '7-4', title: 'Aqaide Nasfiya Sani Saim (54)', urduTitle: 'عقائد نسفیہ ثانی سائم', year: 7, category: 'book', driveLink: '/books/7th Year/Aqaide Nasfiya Sani Saim (54).pdf', image: YEAR_IMAGES[7] },
      { id: '7-5', title: 'Aqaide Nasfiya Sharah (202)', urduTitle: 'عقائد نسفیہ شرح', year: 7, category: 'book', driveLink: '/books/7th Year/Aqaide Nasfiya Sharah (202).pdf', image: YEAR_IMAGES[7] },
      { id: '7-6', title: 'Aqaide Nasfiya Sharah (242)', urduTitle: 'عقائد نسفیہ شرح', year: 7, category: 'book', driveLink: '/books/7th Year/Aqaide Nasfiya Sharah (242).pdf', image: YEAR_IMAGES[7] },
      { id: '7-7', title: 'Aqaide Nasfiya Sharah (553)', urduTitle: 'عقائد نسفیہ شرح', year: 7, category: 'book', driveLink: '/books/7th Year/Aqaide Nasfiya Sharah (553).pdf', image: YEAR_IMAGES[7] },
      { id: '7-8', title: 'Aqaide Nasfiya Sharah (94)', urduTitle: 'عقائد نسفیہ شرح', year: 7, category: 'book', driveLink: '/books/7th Year/Aqaide Nasfiya Sharah (94).pdf', image: YEAR_IMAGES[7] },
      { id: '7-9', title: 'Hidaya Ahsan Ul Hidaya Vol 08', urduTitle: 'الہدایۃ احسن الہدایۃ جلد ۸', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Ahsan Ul Hidaya volume 08.pdf', image: YEAR_IMAGES[7] },
      { id: '7-10', title: 'Hidaya Ahsan Ul Hidaya Vol 09', urduTitle: 'الہدایۃ احسن الہدایۃ جلد ۹', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Ahsan Ul Hidaya volume 09.pdf', image: YEAR_IMAGES[7] },
      { id: '7-11', title: 'Hidaya Ahsan Ul Hidaya Vol 10', urduTitle: 'الہدایۃ احسن الہدایۃ جلد ۱۰', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Ahsan Ul Hidaya volume 10.pdf', image: YEAR_IMAGES[7] },
      { id: '7-12', title: 'Hidaya Ahsan Ul Hidaya Vol 11', urduTitle: 'الہدایۃ احسن الہدایۃ جلد ۱۱', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Ahsan Ul Hidaya volume 11.pdf', image: YEAR_IMAGES[7] },
      { id: '7-13', title: 'Hidaya Ahsan Ul Hidaya Vol 12', urduTitle: 'الہدایۃ احسن الہدایۃ جلد ۱۲', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Ahsan Ul Hidaya volume 12.pdf', image: YEAR_IMAGES[7] },
      { id: '7-14', title: 'Hidaya Ahsan Ul Hidaya Vol 13', urduTitle: 'الہدایۃ احسن الہدایۃ جلد ۱۳', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Ahsan Ul Hidaya volume 13.pdf', image: YEAR_IMAGES[7] },
      { id: '7-15', title: 'Hidaya Ahsan Ul Hidaya Vol 14', urduTitle: 'الہدایۃ احسن الہدایۃ جلد ۱۴', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Ahsan Ul Hidaya volume 14.pdf', image: YEAR_IMAGES[7] },
      { id: '7-16', title: 'Hidaya Ahsan Ul Hidaya Vol 15', urduTitle: 'الہدایۃ احسن الہدایۃ جلد ۱۵', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Ahsan Ul Hidaya volume 15.pdf', image: YEAR_IMAGES[7] },
      { id: '7-17', title: 'Hidaya Ahsan Ul Hidaya Vol 16', urduTitle: 'الہدایۃ احسن الہدایۃ جلد ۱۶', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Ahsan Ul Hidaya volume 16.pdf', image: YEAR_IMAGES[7] },
      { id: '7-18', title: 'Hidaya Awal (104)', urduTitle: 'الہدایۃ اول', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Awal (104).pdf', image: YEAR_IMAGES[7] },
      { id: '7-19', title: 'Hidaya Awal (20)', urduTitle: 'الہدایۃ اول', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Awal (20).pdf', image: YEAR_IMAGES[7] },
      { id: '7-20', title: 'Hidaya Awal (6)', urduTitle: 'الہدایۃ اول', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Awal (6).pdf', image: YEAR_IMAGES[7] },
      { id: '7-21', title: 'Hidaya Awal Ikhtilaf (25)', urduTitle: 'الہدایۃ اول اختلاف', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Awal Ikhtilaf (25).pdf', image: YEAR_IMAGES[7] },
      { id: '7-22', title: 'Hidaya Awal Map (14)', urduTitle: 'الہدایۃ اول میپ', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Awal Map (14).pdf', image: YEAR_IMAGES[7] },
      { id: '7-23', title: 'Hidaya Awal Saim (83)', urduTitle: 'الہدایۃ اول سائم', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Awal Saim (83).pdf', image: YEAR_IMAGES[7] },
      { id: '7-24', title: 'Hidaya MCQs (14)', urduTitle: 'الہدایۃ ایم سی کیوز', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya MCQs (14).pdf', image: YEAR_IMAGES[7] },
      { id: '7-25', title: 'Hidaya Sani (26)', urduTitle: 'الہدایۃ ثانی', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Sani (26).pdf', image: YEAR_IMAGES[7] },
      { id: '7-26', title: 'Hidaya Sani (43)', urduTitle: 'الہدایۃ ثانی', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya sani (43).pdf', image: YEAR_IMAGES[7] },
      { id: '7-27', title: 'Hidaya Sani (85)', urduTitle: 'الہدایۃ ثانی', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya sani (85).pdf', image: YEAR_IMAGES[7] },
      { id: '7-28', title: 'Hidaya Sharah Vol 10', urduTitle: 'الہدایۃ شرح جلد ۱۰', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Sharah Volume 10.pdf', image: YEAR_IMAGES[7] },
      { id: '7-29', title: 'Hidaya Tarifat (4)', urduTitle: 'الہدایۃ تعریفات', year: 7, category: 'book', driveLink: '/books/7th Year/Hidaya Tarifat (4).pdf', image: YEAR_IMAGES[7] },
      { id: '7-30', title: 'Meezanul Adyan (120)', urduTitle: 'میزان الدین', year: 7, category: 'book', driveLink: '/books/7th Year/Meezanul Adyan (120).pdf', image: YEAR_IMAGES[7] },
      { id: '7-31', title: 'Meezanul Adyan (50)', urduTitle: 'میزان الدین', year: 7, category: 'book', driveLink: '/books/7th Year/Meezanul Adyan (50).pdf', image: YEAR_IMAGES[7] },
      { id: '7-32', title: 'Meezanul Adyan MCQs (15)', urduTitle: 'میزان الدین ایم سی کیوز', year: 7, category: 'book', driveLink: '/books/7th Year/Meezanul Adyan MCQs (15).pdf', image: YEAR_IMAGES[7] },
      { id: '7-33', title: 'Meezanul Adyan MCQs (24)', urduTitle: 'میزان الدین ایم سی کیوز', year: 7, category: 'book', driveLink: '/books/7th Year/Meezanul Adyan MCQs (24).pdf', image: YEAR_IMAGES[7] },
      { id: '7-34', title: 'Mezaanul Adyan Saim (86)', urduTitle: 'میزان الدین سائم', year: 7, category: 'book', driveLink: '/books/7th Year/Mezaanul Adyan Saim (86).pdf', image: YEAR_IMAGES[7] },
      { id: '7-35', title: 'Mouta Imam Malik (20)', urduTitle: 'موطا امام مالک', year: 7, category: 'book', driveLink: '/books/7th Year/Mouta Imam Malik (20).pdf', image: YEAR_IMAGES[7] },
      { id: '7-36', title: 'Mouta Imam Malik (25)', urduTitle: 'موطا امام مالک', year: 7, category: 'book', driveLink: '/books/7th Year/Mouta Imam Malik (25).pdf', image: YEAR_IMAGES[7] },
      { id: '7-37', title: 'Mouta Imam Malik (30)', urduTitle: 'موطا امام مالک', year: 7, category: 'book', driveLink: '/books/7th Year/Mouta Imam Malik (30).pdf', image: YEAR_IMAGES[7] },
      { id: '7-38', title: 'Mouta Imam Malik (46)', urduTitle: 'موطا امام مالک', year: 7, category: 'book', driveLink: '/books/7th Year/Mouta Imam Malik (46).pdf', image: YEAR_IMAGES[7] },
      { id: '7-39', title: 'Mouta Imam Malik Saim (55)', urduTitle: 'موطا امام مالک سائم', year: 7, category: 'book', driveLink: '/books/7th Year/Mouta Imam Malik Saim (55).pdf', image: YEAR_IMAGES[7] },
      { id: '7-40', title: 'Mouta Imam Malik Sharah', urduTitle: 'موطا امام مالک شرح', year: 7, category: 'book', driveLink: '/books/7th Year/Mouta Imam Malik Sharah.pdf', image: YEAR_IMAGES[7] },
      { id: '7-41', title: 'Mouta Imam Muhammad (21)', urduTitle: 'موطا امام محمد', year: 7, category: 'book', driveLink: '/books/7th Year/Mouta Imam Muhammad (21).pdf', image: YEAR_IMAGES[7] },
      { id: '7-42', title: 'Mouta Imam Muhammad (48)', urduTitle: 'موطا امام محمد', year: 7, category: 'book', driveLink: '/books/7th Year/Mouta Imam Muhammad (48).pdf', image: YEAR_IMAGES[7] },
      { id: '7-43', title: 'Mouta Imam Muhammad Ikhtilaf (40)', urduTitle: 'موطا امام محمد اختلاف', year: 7, category: 'book', driveLink: '/books/7th Year/Mouta Imam Muhammad Ikhtilaf (40).pdf', image: YEAR_IMAGES[7] },
      { id: '7-44', title: 'Mouta Imam Muhammad MCQs (9)', urduTitle: 'موطا امام محمد ایم سی کیوز', year: 7, category: 'book', driveLink: '/books/7th Year/Mouta Imam Muhammad MCQs (9).pdf', image: YEAR_IMAGES[7] },
      { id: '7-45', title: 'Mouta Imam Muhammad Saim (43)', urduTitle: 'موطا امام محمد سائم', year: 7, category: 'book', driveLink: '/books/7th Year/Mouta Imam Muhammad Saim (43).pdf', image: YEAR_IMAGES[7] },
      { id: '7-46', title: 'Sharah Maani Al Asaar (120)', urduTitle: 'شرح معانی الآثار', year: 7, category: 'book', driveLink: '/books/7th Year/Sharah Maani Al Asaar (120).pdf', image: YEAR_IMAGES[7] },
      { id: '7-47', title: 'Sharah Maani Al Asaar (32)', urduTitle: 'شرح معانی الآثار', year: 7, category: 'book', driveLink: '/books/7th Year/Sharah Maani Al Asaar (32).pdf', image: YEAR_IMAGES[7] },
      { id: '7-48', title: 'Sharah Maani Al Asaar (42)', urduTitle: 'شرح معانی الآثار', year: 7, category: 'book', driveLink: '/books/7th Year/Sharah Maani Al Asaar (42).pdf', image: YEAR_IMAGES[7] },
      { id: '7-49', title: 'Sharah Maani Al Asaar MCQs (12)', urduTitle: 'شرح معانی الآثار ایم سی کیوز', year: 7, category: 'book', driveLink: '/books/7th Year/Sharah Maani Al Asaar MCQs (12).pdf', image: YEAR_IMAGES[7] },
      { id: '7-50', title: 'Sharah Maani Al Asaar Saim (48)', urduTitle: 'شرح معانی الآثار سائم', year: 7, category: 'book', driveLink: '/books/7th Year/Sharah Maani Al Asaar Saim (48).pdf', image: YEAR_IMAGES[7] },
      { id: '7-51', title: 'Sharah Maani Al Asaar Sharah (293)', urduTitle: 'شرح معانی الآثار شرح', year: 7, category: 'book', driveLink: '/books/7th Year/Sharah Maani Al Asaar Sharah (293).pdf', image: YEAR_IMAGES[7] },
      { id: '7-52', title: 'Sharah Nukhba (93)', urduTitle: 'شرح النخبۃ', year: 7, category: 'book', driveLink: '/books/7th Year/Sharah Nukhba (93).pdf', image: YEAR_IMAGES[7] },
      { id: '7-53', title: 'Sharah Nukhba Saim (80)', urduTitle: 'شرح النخبۃ سائم', year: 7, category: 'book', driveLink: '/books/7th Year/Sharah Nukhba Saim (80).pdf', image: YEAR_IMAGES[7] },
      { id: '7-54', title: 'Sharah Nukhba Sharah (373)', urduTitle: 'شرح النخبۃ شرح', year: 7, category: 'book', driveLink: '/books/7th Year/Sharah Nukhba Sharah (373).pdf', image: YEAR_IMAGES[7] },
      { id: '7-55', title: 'Sharah Nukhba Sharah (473)', urduTitle: 'شرح النخبۃ شرح', year: 7, category: 'book', driveLink: '/books/7th Year/Sharah Nukhba Sharah (473).pdf', image: YEAR_IMAGES[7] },
      { id: '7-56', title: 'Siraji (109)', urduTitle: 'السراجی', year: 7, category: 'book', driveLink: '/books/7th Year/Siraji (109).pdf', image: YEAR_IMAGES[7] },
      { id: '7-57', title: 'Siraji (22)', urduTitle: 'السراجی', year: 7, category: 'book', driveLink: '/books/7th Year/Siraji (22).pdf', image: YEAR_IMAGES[7] },
      { id: '7-58', title: 'Siraji (25)', urduTitle: 'السراجی', year: 7, category: 'book', driveLink: '/books/7th Year/Siraji (25).pdf', image: YEAR_IMAGES[7] },
      { id: '7-59', title: 'Siraji (73)', urduTitle: 'السراجی', year: 7, category: 'book', driveLink: '/books/7th Year/Siraji (73).pdf', image: YEAR_IMAGES[7] },
      { id: '7-60', title: 'Siraji MCQs (13)', urduTitle: 'السراجی ایم سی کیوز', year: 7, category: 'book', driveLink: '/books/7th Year/Siraji MCQs (13).pdf', image: YEAR_IMAGES[7] },
      { id: '7-61', title: 'Siraji MCQs (45)', urduTitle: 'السراجی ایم سی کیوز', year: 7, category: 'book', driveLink: '/books/7th Year/Siraji MCQs (45).pdf', image: YEAR_IMAGES[7] },
      { id: '7-62', title: 'Siraji Saim (30)', urduTitle: 'السراجی سائم', year: 7, category: 'book', driveLink: '/books/7th Year/Siraji Saim (30).pdf', image: YEAR_IMAGES[7] },
      { id: '7-63', title: 'Siraji Sharah (196)', urduTitle: 'السراجی شرح', year: 7, category: 'book', driveLink: '/books/7th Year/Siraji Sharah (196).pdf', image: YEAR_IMAGES[7] },
      { id: '7-64', title: 'Siraji Sharah (334)', urduTitle: 'السراجی شرح', year: 7, category: 'book', driveLink: '/books/7th Year/Siraji Sharah (334).pdf', image: YEAR_IMAGES[7] },
      { id: '7-65', title: 'Siraji Tarifaat (6)', urduTitle: 'السراجی تعریفات', year: 7, category: 'book', driveLink: '/books/7th Year/Siraji Tarifaat (6).pdf', image: YEAR_IMAGES[7] },
      { id: '7-66', title: 'Tehqeeqo Tadween (44)', urduTitle: 'تحقیق و تدوین', year: 7, category: 'book', driveLink: '/books/7th Year/Tehqeeqo Tadween (44).pdf', image: YEAR_IMAGES[7] },
      { id: '7-67', title: 'Tehqeeqo Tadween (53)', urduTitle: 'تحقیق و تدوین', year: 7, category: 'book', driveLink: '/books/7th Year/Tehqeeqo Tadween (53).pdf', image: YEAR_IMAGES[7] },
      { id: '7-68', title: 'Tehqeeqo Tadween Book', urduTitle: 'تحقیق و تدوین کتاب', year: 7, category: 'book', driveLink: '/books/7th Year/Tehqeeqo Tadween Book.pdf', image: YEAR_IMAGES[7] },
      { id: '7-69', title: 'Tehqeeqo Tadween Map (6)', urduTitle: 'تحقیق و تدوین میپ', year: 7, category: 'book', driveLink: '/books/7th Year/Tehqeeqo Tadween Map (6).pdf', image: YEAR_IMAGES[7] },
      { id: '7-70', title: 'Tehqeeqo Tadween MCQs (6)', urduTitle: 'تحقیق و تدوین ایم سی کیوز', year: 7, category: 'book', driveLink: '/books/7th Year/Tehqeeqo Tadween MCQs (6).pdf', image: YEAR_IMAGES[7] },
      { id: '7-71', title: 'Tehqeeqo Tadween Saim (78)', urduTitle: 'تحقیق و تدوین سائم', year: 7, category: 'book', driveLink: '/books/7th Year/Tehqeeqo Tadween Saim (78).pdf', image: YEAR_IMAGES[7] },
      { id: '7-72', title: 'Tozeeho Talweeh (121)', urduTitle: 'توضیح التلویح', year: 7, category: 'book', driveLink: '/books/7th Year/Tozeeho Talweeh (121).pdf', image: YEAR_IMAGES[7] },
      { id: '7-73', title: 'Tozeeho Talweeh (28)', urduTitle: 'توضیح التلویح', year: 7, category: 'book', driveLink: '/books/7th Year/Tozeeho Talweeh (28).pdf', image: YEAR_IMAGES[7] },
      { id: '7-74', title: 'Tozeeho Talweeh (31)', urduTitle: 'توضیح التلویح', year: 7, category: 'book', driveLink: '/books/7th Year/Tozeeho Talweeh (31).pdf', image: YEAR_IMAGES[7] },
      { id: '7-75', title: 'Tozeeho Talweeh (37)', urduTitle: 'توضیح التلویح', year: 7, category: 'book', driveLink: '/books/7th Year/Tozeeho Talweeh (37).pdf', image: YEAR_IMAGES[7] },
      { id: '7-76', title: 'Tozeeho Talweeh Map (13)', urduTitle: 'توضیح التلویح میپ', year: 7, category: 'book', driveLink: '/books/7th Year/Tozeeho Talweeh Map (13).pdf', image: YEAR_IMAGES[7] },
      { id: '7-77', title: 'Tozeeho Talweeh MCQs (13)', urduTitle: 'توضیح التلویح ایم سی کیوز', year: 7, category: 'book', driveLink: '/books/7th Year/Tozeeho Talweeh MCQs (13).pdf', image: YEAR_IMAGES[7] },
      { id: '7-78', title: 'Tozeeho Talweeh Saim (44)', urduTitle: 'توضیح التلویح سائم', year: 7, category: 'book', driveLink: '/books/7th Year/Tozeeho Talweeh Saim (44).pdf', image: YEAR_IMAGES[7] },
      { id: '7-79', title: 'Tozeeho Talweeh Sharah (145)', urduTitle: 'توضیح التلویح شرح', year: 7, category: 'book', driveLink: '/books/7th Year/Tozeeho Talweeh Sharah (145).pdf', image: YEAR_IMAGES[7] },
      { id: '7-80', title: 'Tozeeho Talweeh Sharah (299)', urduTitle: 'توضیح التلویح شرح', year: 7, category: 'book', driveLink: '/books/7th Year/Tozeeho Talweeh Sharah (299).pdf', image: YEAR_IMAGES[7] },
      { id: '7-81', title: 'Tozeeho Talweeh Sharah (499)', urduTitle: 'توضیح التلویح شرح', year: 7, category: 'book', driveLink: '/books/7th Year/Tozeeho Talweeh Sharah (499).pdf', image: YEAR_IMAGES[7] },
      { id: '7-82', title: 'Khulasa Sharah Aqaid Saim Awal', urduTitle: 'خلاصہ شرح عقائد ششماہی اول', year: 7, category: 'book', driveLink: '/books/7th Year/خلاصہ شرح عقائد ششماہی اول.pdf', image: YEAR_IMAGES[7] },
      { id: '7-83', title: 'Khulasa Sharah Aqaid Sani', urduTitle: 'خلاصہ شرح عقائد ششماہی ثانی', year: 7, category: 'book', driveLink: '/books/7th Year/خلاصہ شرح عقائد ششماہی ثانی.pdf', image: YEAR_IMAGES[7] },
      { id: '7-84', title: 'Hidaya Kitabul Buyoo', urduTitle: 'نوٹس ھدایہ کتاب البیوع', year: 7, category: 'book', driveLink: '/books/7th Year/نوٹس ھدایہ کتاب البیوع.pdf', image: YEAR_IMAGES[7] },
    ],
    sharahs: [],
    papers: [],
  },
  {
    year: 8,
    name: 'Darja Dorah Hadeese (8th Year)',
    urduName: ' درجہ دورة الحديث ',
    books: [
      { id: '8-1', title: 'Abi Dawood Awal Q&A (47)', urduTitle: 'ابی داؤد اول سوال جواب', year: 8, category: 'book', driveLink: '/books/8th Year/Abi Dawood awal Question Answer (47).pdf', image: YEAR_IMAGES[8] },
      { id: '8-2', title: 'Abi Dawood Awal Saim (61)', urduTitle: 'ابی داؤد اول سائم', year: 8, category: 'book', driveLink: '/books/8th Year/Abi Dawood Awal Saim (61).pdf', image: YEAR_IMAGES[8] },
      { id: '8-3', title: 'Abi Dawood Awal Talkhees (35)', urduTitle: 'ابی داؤد اول تلخیص', year: 8, category: 'book', driveLink: '/books/8th Year/Abi Dawood Awal Talkhees (35).pdf', image: YEAR_IMAGES[8] },
      { id: '8-4', title: 'Abi Dawood Sharah (643)', urduTitle: 'ابی داؤد شرح', year: 8, category: 'book', driveLink: '/books/8th Year/Abi Dawood Sharah 643.pdf', image: YEAR_IMAGES[8] },
      { id: '8-5', title: 'Abi Dawood Tarjama (723)', urduTitle: 'ابی داؤد ترجمہ', year: 8, category: 'book', driveLink: '/books/8th Year/Abi Dawood Tarjama (723).pdf', image: YEAR_IMAGES[8] },
      { id: '8-6', title: 'Al Arabiyah (131)', urduTitle: 'العربیۃ', year: 8, category: 'book', driveLink: '/books/8th Year/Al Arabiyah (131).pdf', image: YEAR_IMAGES[8] },
      { id: '8-7', title: 'Al Arabiyah Arabic (85)', urduTitle: 'العربیۃ عربی', year: 8, category: 'book', driveLink: '/books/8th Year/Al Arabiyah Arabic (85).pdf', image: YEAR_IMAGES[8] },
      { id: '8-8', title: 'Al Arabiyah Urdu (69)', urduTitle: 'العربیۃ اردو', year: 8, category: 'book', driveLink: '/books/8th Year/Al Arabiyah Urdu (69).pdf', image: YEAR_IMAGES[8] },
      { id: '8-9', title: 'Bukhari Awal Q&A (168)', urduTitle: 'بخاری اول سوال جواب', year: 8, category: 'book', driveLink: '/books/8th Year/Bukhari awal Question Answer (168).pdf', image: YEAR_IMAGES[8] },
      { id: '8-10', title: 'Bukhari Awal Saim (73)', urduTitle: 'بخاری اول سائم', year: 8, category: 'book', driveLink: '/books/8th Year/Bukhari Awal Saim (73).pdf', image: YEAR_IMAGES[8] },
      { id: '8-11', title: 'Bukhari Awal Talkhees (38)', urduTitle: 'بخاری اول تلخیص', year: 8, category: 'book', driveLink: '/books/8th Year/Bukhari Awal Talkhees (38).pdf', image: YEAR_IMAGES[8] },
      { id: '8-12', title: 'Bukhari Book Arabic Altaf', urduTitle: 'بخاری کتاب عربی', year: 8, category: 'book', driveLink: '/books/8th Year/Bukhari Book Arabic Altaf sons.pdf', image: YEAR_IMAGES[8] },
      { id: '8-13', title: 'Bukhari Book Arabic', urduTitle: 'بخاری کتاب عربی', year: 8, category: 'book', driveLink: '/books/8th Year/Bukhari Book Arabic.pdf', image: YEAR_IMAGES[8] },
      { id: '8-14', title: 'Bukhari MCQs', urduTitle: 'بخاری ایم سی کیوز', year: 8, category: 'book', driveLink: '/books/8th Year/Bukhari MCQs.pdf', image: YEAR_IMAGES[8] },
      { id: '8-15', title: 'Bukhari Sharah (899)', urduTitle: 'بخاری شرح', year: 8, category: 'book', driveLink: '/books/8th Year/Bukhari Sharah (899).pdf', image: YEAR_IMAGES[8] },
      { id: '8-16', title: 'Bukhari Sharah Nuzha Vol 1', urduTitle: 'بخاری شرح نزهۃ القاری جلد ۱', year: 8, category: 'book', driveLink: '/books/8th Year/Bukhari Sharah Nuzha tul Qari jild 1.pdf', image: YEAR_IMAGES[8] },
      { id: '8-17', title: 'Bukhari Tarjama (1032)', urduTitle: 'بخاری ترجمہ', year: 8, category: 'book', driveLink: '/books/8th Year/Bukhari Tarjama (1032).pdf', image: YEAR_IMAGES[8] },
      { id: '8-18', title: 'Bukhari Tarjama (1090)', urduTitle: 'بخاری ترجمہ', year: 8, category: 'book', driveLink: '/books/8th Year/Bukhari Trjama (1090).pdf', image: YEAR_IMAGES[8] },
      { id: '8-19', title: 'Ibne Majah Awal Q&A (53)', urduTitle: 'ابن ماجہ اول سوال جواب', year: 8, category: 'book', driveLink: '/books/8th Year/Ibne Majah awal Question Answer (53).pdf', image: YEAR_IMAGES[8] },
      { id: '8-20', title: 'Muslim Awal Q&A (91)', urduTitle: 'مسلم اول سوال جواب', year: 8, category: 'book', driveLink: '/books/8th Year/Muslim awal Question Answer (91).pdf', image: YEAR_IMAGES[8] },
      { id: '8-21', title: 'Muslim Awal Saim (52)', urduTitle: 'مسلم اول سائم', year: 8, category: 'book', driveLink: '/books/8th Year/Muslim Awal Saim (52).pdf', image: YEAR_IMAGES[8] },
      { id: '8-22', title: 'Muslim Awal Talkhees (29)', urduTitle: 'مسلم اول تلخیص', year: 8, category: 'book', driveLink: '/books/8th Year/Muslim Awal Talkhees (29).pdf', image: YEAR_IMAGES[8] },
      { id: '8-23', title: 'Muslim Tarjama (1145)', urduTitle: 'مسلم ترجمہ', year: 8, category: 'book', driveLink: '/books/8th Year/Muslim Tarjama (1145).pdf', image: YEAR_IMAGES[8] },
      { id: '8-24', title: 'Nasai Awal Q&A (37)', urduTitle: 'نسائی اول سوال جواب', year: 8, category: 'book', driveLink: '/books/8th Year/Nasai awal Question Answer (37).pdf', image: YEAR_IMAGES[8] },
      { id: '8-25', title: 'Nasai Saim (36)', urduTitle: 'نسائی سائم', year: 8, category: 'book', driveLink: '/books/8th Year/Nisai Saim (36).pdf', image: YEAR_IMAGES[8] },
      { id: '8-26', title: 'Tirmizi Awal Q&A (66)', urduTitle: 'ترمذی اول سوال جواب', year: 8, category: 'book', driveLink: '/books/8th Year/Tirmizi awal Question Answer (66).pdf', image: YEAR_IMAGES[8] },
      { id: '8-27', title: 'Tirmizi Awal Saim (54)', urduTitle: 'ترمذی اول سائم', year: 8, category: 'book', driveLink: '/books/8th Year/Tirmizi Awal Saim (54).pdf', image: YEAR_IMAGES[8] },
      { id: '8-28', title: 'Tirmizi Imsaal (211)', urduTitle: 'ترمذی امثال', year: 8, category: 'book', driveLink: '/books/8th Year/Tirmizi Imsaal (211).pdf', image: YEAR_IMAGES[8] },
      { id: '8-29', title: 'Tirmizi Sharah (858)', urduTitle: 'ترمذی شرح', year: 8, category: 'book', driveLink: '/books/8th Year/Tirmizi Sharah (858).pdf', image: YEAR_IMAGES[8] },
      { id: '8-30', title: 'Tirmizi Sharah Vol 1 (1044)', urduTitle: 'ترمذی شرح جلد ۱', year: 8, category: 'book', driveLink: '/books/8th Year/Tirmizi Sharah jild 01 (1044).pdf', image: YEAR_IMAGES[8] },
      { id: '8-31', title: 'Tirmizi Sharah Vol 1 (692)', urduTitle: 'ترمذی شرح جلد ۱', year: 8, category: 'book', driveLink: '/books/8th Year/Tirmizi Sharah jild 01 (692).pdf', image: YEAR_IMAGES[8] },
      { id: '8-32', title: 'Bab Fadhail Madinah', urduTitle: 'باب فضائلِ مدینہ', year: 8, category: 'book', driveLink: '/books/8th Year/باب فضائلِ مدینہ.pdf', image: YEAR_IMAGES[8] },
      { id: '8-33', title: 'Kitab Al Adaab Muslim', urduTitle: 'کتاب الآداب المسلم شریف', year: 8, category: 'book', driveLink: '/books/8th Year/کتاب الآداب المسلم شریف.pdf', image: YEAR_IMAGES[8] },
      { id: '8-34', title: 'Muslim Kitabul Buyoo', urduTitle: 'مسلم شریف الکتاب البیوع', year: 8, category: 'book', driveLink: '/books/8th Year/مسلم شریف الکتاب البیوع.pdf', image: YEAR_IMAGES[8] },
    ],
    sharahs: [],
    papers: [],
  },
];

// Paper Aaliya Part 1 - All papers from folders
export const paperAaliya01: Book[] = [
  // 2023 Solve
  { id: 'aaliya01-1', title: '2023 Solve الادب العربی', urduTitle: '2023 حل الادب العربی عالیہ اول', year: 'Aaliya 01', category: 'paper', driveLink: '/books/Paper Aaliya 01/2023 Solve عالیہ سال اول/2023 Solve الادب العربی عالیہ اول.pdf', image: PAPER_IMAGE },
  { id: 'aaliya01-2', title: '2023 Solve السیرۃ النبویۃ+العقیدۃ', urduTitle: '2023 حل السیرۃ والعقیدہ عالیہ اول', year: 'Aaliya 01', category: 'paper', driveLink: '/books/Paper Aaliya 01/2023 Solve عالیہ سال اول/2023 Solve السیرۃ النبویۃ+العقیدۃ عالیہ اول.pdf', image: PAPER_IMAGE },
  { id: 'aaliya01-3', title: '2023 Solve الفقہ', urduTitle: '2023 حل الفقہ عالیہ اول', year: 'Aaliya 01', category: 'paper', driveLink: '/books/Paper Aaliya 01/2023 Solve عالیہ سال اول/2023 Solve الفقہ عالیہ اول.pdf', image: PAPER_IMAGE },
  { id: 'aaliya01-4', title: '2023 Solve علوم الفقہ', urduTitle: '2023 حل علوم الفقہ عالیہ اول', year: 'Aaliya 01', category: 'paper', driveLink: '/books/Paper Aaliya 01/2023 Solve عالیہ سال اول/2023 Solve علوم الفقہ عالیہ اول.pdf', image: PAPER_IMAGE },
  // 2024
  { id: 'aaliya01-5', title: '2024 Solve علوم الفقہ', urduTitle: '2024 حل علوم الفقہ عالیہ اول', year: 'Aaliya 01', category: 'paper', driveLink: '/books/Paper Aaliya 01/2024/2024 Solve علوم الفقہ عالیہ اول.pdf', image: PAPER_IMAGE },
  { id: 'aaliya01-6', title: '2024 البلاغۃ', urduTitle: '2024 البلاغۃ عالیہ اول', year: 'Aaliya 01', category: 'paper', driveLink: '/books/Paper Aaliya 01/2024/2024 البلاغۃ.pdf', image: PAPER_IMAGE },
];

// Paper Aaliya Part 2 - All papers from folders
export const paperAaliya02: Book[] = [
  // Root folder papers
  { id: 'aaliya02-1', title: 'Aalmiya Part 2 2023', urduTitle: 'عالمیہ سال دوم 2023', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/عالمیہ سال دوم 2023.pdf', image: PAPER_IMAGE },
  { id: 'aaliya02-2', title: 'Aalmiya Part 2 2024', urduTitle: 'عالمیہ سال دوم 2024', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/عالمیہ سال دوم 2024.pdf', image: PAPER_IMAGE },
  { id: 'aaliya02-3', title: 'Aalmiya Part 2 2025', urduTitle: 'عالمیہ سال دوم 2025', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/عالمیہ سال دوم 2025.pdf', image: PAPER_IMAGE },
  { id: 'aaliya02-4', title: 'Tirmizi Sharah Solved 23,24,25', urduTitle: 'حل شدہ ترمذی شریف 23,24,25', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/حل شدہ ترمذی شریف 23,24,25(1).pdf', image: PAPER_IMAGE },
  { id: 'aaliya02-5', title: 'Sunan Nasai & Ibne Majah Solved', urduTitle: 'سنن نسائی و سنن ابن ماجہ حل شدہ', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/سنن نسائی و سنن ابن ماجہ حل شدہ (1).pdf', image: PAPER_IMAGE },
  // 2023 folder
  { id: 'aaliya02-6', title: '2023 Solve Aqeeda', urduTitle: '2023 حل عقیدہ', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/2023/2023 Solve Aqeeda.pdf', image: PAPER_IMAGE },
  { id: 'aaliya02-7', title: '2023 Solve الفقہ', urduTitle: '2023 حل الفقہ', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/2023/2023. الفقہ.pdf', image: PAPER_IMAGE },
  // Solved 2024
  { id: 'aaliya02-8', title: 'Solve 2024 التصوف', urduTitle: 'حل 2024 التصوف', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/Solved  2024/Solve  2024التصوف.pdf', image: PAPER_IMAGE },
  { id: 'aaliya02-9', title: 'Solve 2024 Fiqh', urduTitle: 'حل 2024 فقہ', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/Solved  2024/Solve  Fiqh 2024.pdf', image: PAPER_IMAGE },
  { id: 'aaliya02-10', title: 'Solve 2024 Aqeeda', urduTitle: 'حل 2024 عقیدہ', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/Solved  2024/solve Aqeeda  2024.pdf', image: PAPER_IMAGE },
  { id: 'aaliya02-11', title: 'Solve 2024 Hadeese', urduTitle: 'حل 2024 حدیث', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/Solved  2024/Solve Hadeese 2024.pdf', image: PAPER_IMAGE },
  { id: 'aaliya02-12', title: 'Solve 2024 الدعوۃ', urduTitle: 'حل 2024 الدعوۃ', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/Solved  2024/حل شدہ الدعوۃ انشائیہ 2024.pdf', image: PAPER_IMAGE },
  // Solves 2025
  { id: 'aaliya02-13', title: '2025 Solve التفسیر', urduTitle: '2025 حل التفسیر', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/Solves 2025/1. عالیہ سال دوم التفسیر انشائیہ سالانہ.pdf', image: PAPER_IMAGE },
  { id: 'aaliya02-14', title: '2025 Solve الحدیث', urduTitle: '2025 حل الحدیث', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/Solves 2025/2. عالیہ سال دوم الحدیث الشریف انشائیہ سالانہ.pdf', image: PAPER_IMAGE },
  { id: 'aaliya02-15', title: '2025 Solve المناظرۃ', urduTitle: '2025 حل المناظرۃ', year: 'Aaliya 02', category: 'paper', driveLink: '/books/Paper Aaliya 02/Solves 2025/6. المناظرۃ + الفلسفۃ.pdf', image: PAPER_IMAGE },
];

// Paper Aalmiya Part 1
export const paperAalmiya01: Book[] = [
  // Root folder - Main papers
  { id: 'aalmiya01-1', title: 'Aalmiya Part 1 2023', urduTitle: 'عالمیہ پارٹ 1 (2023)', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/aalmiya-part-1 (2023).pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-2', title: 'Aalmiya Part 1 2024', urduTitle: 'عالمیہ پارٹ 1 (2024)', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/aalmiya-part-1 (2024).pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-3', title: 'Aalmiya Part 1 2025', urduTitle: 'عالمیہ پارٹ 1 (2025)', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/aalmiya-part-1 (2025).pdf', image: PAPER_IMAGE },
  // Root folder - Tahawi + Ulum Hadith
  { id: 'aalmiya01-4', title: 'Tahawi + Ulum Hadith 2023', urduTitle: 'عالمیہ سال اول ۔۔ طحاوی+ علوم حدیث 2023', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/عالمیہ سال اول ۔۔      طحاوی+علوم حدیث 2023.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-5', title: 'Hadith (Tahawi) + Ulum Hadith 2024', urduTitle: 'عالمیہ سال اول ۔۔ حدیث (طحاوی )+علوم حدیث 2024', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/عالمیہ سال اول ۔۔ حدیث (طحاوی )+علوم حدیث 2024.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-6', title: 'Tahawi + Ulum Hadith 2025', urduTitle: 'عالمیہ سال اول طحاوی+علوم حدیث 2025', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/عالمیہ سال اول طحاوی+علوم حدیث 2025.pdf', image: PAPER_IMAGE },
  // Solved 2025
  { id: 'aalmiya01-7', title: '2025 Solve العقیدۃ', urduTitle: '2025 حل العقیدۃ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Solved 2025/3. العقیدۃ.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-8', title: '2025 Solve مقارنۃ الادیان', urduTitle: '2025 حل مقارنۃ الادیان', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Solved 2025/4. مقارنۃ الادیان.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-9', title: '2025 Solve الفقه', urduTitle: '2025 حل الفقه', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Solved 2025/5. الفقه.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-10', title: '2025 Solve علوم الفقه', urduTitle: '2025 حل علوم الفقه', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Solved 2025/6. علوم الفقه.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-11', title: '2025 Solve اصول تحقیق', urduTitle: '2025 حل اصول تحقیق', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Solved 2025/8. اصول تحقیق.pdf', image: PAPER_IMAGE },
  // Solved folder - Major works
  { id: 'aalmiya01-12', title: 'حل شدہ تمام پیپرز نخبت الفکر', urduTitle: 'حل شدہ نخبت الفکر', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Solved/حل شدہ تمام پیپرز نخبت الفکر.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-13', title: 'حل شدہ مؤطین تمام پیپرز', urduTitle: 'حل شدہ مؤطین', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Solved/حل شدہ مؤطین تمام پیپرز.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-14', title: 'سابقہ توضیح تمام پیپرز حل', urduTitle: 'سابقہ توضیح حل', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Solved/سابقہ توضیح تمام پیپرز حل.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-15', title: 'سابقہ عقائد نسفیہ حل شدہ پیپرز', urduTitle: 'عقائد نسفیہ حل شدہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Solved/سابقہ عقائد نسفیہ حل شدہ پیپرز.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-16', title: 'سابقہ میزان حل شدہ پیپرز', urduTitle: 'میزان حل شدہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Solved/سابقہ میزان حل شدہ پیپرز.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-17', title: 'سابقہ ھدایہ پیپرز', urduTitle: 'ھدایہ پیپرز', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Solved/سابقہ ھدایہ پیپرز.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-18', title: 'سراجی حل شدہ پیپر', urduTitle: 'سراجی حل شدہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Solved/سراجی حل شدہ پیپر.pdf', image: PAPER_IMAGE },
  // Solved 2023,24,25
  { id: 'aalmiya01-19', title: 'طحاوی و اصول حدیث حل شدہ', urduTitle: 'طحاوی و اصول حدیث 3 سالہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/solved 2023,24,25/طحاوی و اصول حدیث۔ حل شدہ تین سالہ.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-20', title: 'کنزالمدارس اصول تحقیق 3 سالہ', urduTitle: 'اصول تحقیق 3 سالہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/solved 2023,24,25/کنزالمدارس اصول تحقیق تین سالہ حل شدہ .pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-21', title: 'کنزالمدارس التوضیح والتلویح 3 سالہ', urduTitle: 'التوضیح والتلویح 3 سالہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/solved 2023,24,25/کنزالمدارس التوضیح والتلویح تین سالہ حل شدہ  .pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-22', title: 'کنزالمدارس الفرائض 3 سالہ', urduTitle: 'الفرائض 3 سالہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/solved 2023,24,25/کنزالمدارس الفرائض تین سالہ حل شدہ .pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-23', title: 'کنزالمدارس شرح عقائد نسفیہ 3 سالہ', urduTitle: 'شرح عقائد نسفیہ 3 سالہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/solved 2023,24,25/کنزالمدارس شرح عقائد نسفیہ تین سالہ حل شدہ  .pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-24', title: 'کنزالمدارس طحاوی و اصول حدیث 3 سالہ', urduTitle: 'طحاوی و اصول حدیث 3 سالہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/solved 2023,24,25/کنزالمدارس طحاوی و اصول حدیث حل شدہ تین سالہ  .pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-25', title: 'کنزالمدارس فقہ (ہدایہ) 3 سالہ', urduTitle: 'فقہ ہدایہ 3 سالہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/solved 2023,24,25/کنزالمدارس فقہ ( ہدایہ ) تین سالہ حل شدہ .pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-26', title: 'کنزالمدارس مؤطین 3 سالہ', urduTitle: 'مؤطین 3 سالہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/solved 2023,24,25/کنزالمدارس مؤطین تین سالہ حل شدہ .pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-27', title: 'کنزالمدارس مقارنۃ الادیان 3 سالہ', urduTitle: 'مقارنۃ الادیان 3 سالہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/solved 2023,24,25/کنزالمدارس مقارنۃ الادیان تین سالہ حل شدہ .pdf', image: PAPER_IMAGE },
  // Jamia 2024 Question Papers
  { id: 'aalmiya01-28', title: '2024 الفقہ انشائیہ', urduTitle: '2024 الفقہ انشائیہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Jamia 2024 shishmahi Question paper/1. الفقہ انشائیہ.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-29', title: '2024 علوم الحدیث انشائیہ', urduTitle: '2024 علوم الحدیث انشائیہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Jamia 2024 shishmahi Question paper/2.علوم الحدیث انشائیہ.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-30', title: '2024 الحدیث انشائیہ', urduTitle: '2024 الحدیث انشائیہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Jamia 2024 shishmahi Question paper/3. الحدیث انشائیہ.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-31', title: '2024 علوم الفقہ انشائیہ', urduTitle: '2024 علوم الفقہ انشائیہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Jamia 2024 shishmahi Question paper/4. علوم الفقہ انشائیہ.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-32', title: '2024 العقائد انشائیہ', urduTitle: '2024 العقائد انشائیہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Jamia 2024 shishmahi Question paper/5. العقائد انشائیہ.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya01-33', title: '2024 اصول تحقیق انشائیہ', urduTitle: '2024 اصول تحقیق انشائیہ', year: 'Aalmiya 01', category: 'paper', driveLink: '/books/Paper Aalmiya  01/Jamia 2024 shishmahi Question paper/6. اصول تحقیق انشائیہ.pdf', image: PAPER_IMAGE },
];

// Paper Aalmiya Part 2
export const paperAalmiya02: Book[] = [
  // Root folder - Main papers
  { id: 'aalmiya02-1', title: 'Aalmiya Part 2 2023', urduTitle: 'عالمیہ سال دوم 2023', year: 'Aalmiya 02', category: 'paper', driveLink: '/books/Paper Aalmiya  02/عالمیہ سال دوم 2023.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya02-2', title: 'Aalmiya Part 2 2024', urduTitle: 'عالمیہ سال دوم 2024', year: 'Aalmiya 02', category: 'paper', driveLink: '/books/Paper Aalmiya  02/عالمیہ سال دوم 2024.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya02-3', title: 'Aalmiya Part 2 2025', urduTitle: 'عالمیہ سال دوم 2025', year: 'Aalmiya 02', category: 'paper', driveLink: '/books/Paper Aalmiya  02/عالمیہ سال دوم 2025.pdf', image: PAPER_IMAGE },
  // Root folder - Solved papers
  { id: 'aalmiya02-4', title: 'Tirmizi Sharah Solved 23,24,25', urduTitle: 'حل شدہ ترمذی شریف 23,24,25', year: 'Aalmiya 02', category: 'paper', driveLink: '/books/Paper Aalmiya  02/حل شدہ ترمذی شریف 23,24,25(1).pdf', image: PAPER_IMAGE },
  { id: 'aalmiya02-5', title: 'Sunan Nasai & Ibne Majah Solved', urduTitle: 'سنن نسائی و سنن ابن ماجہ حل شدہ', year: 'Aalmiya 02', category: 'paper', driveLink: '/books/Paper Aalmiya  02/سنن نسائی و سنن ابن ماجہ حل شدہ (1).pdf', image: PAPER_IMAGE },
  // Solved 23,24,25 folder
  { id: 'aalmiya02-6', title: '2023 Bukhari Shareef', urduTitle: '2023 بخاری شریف', year: 'Aalmiya 02', category: 'paper', driveLink: '/books/Paper Aalmiya  02/Solved 23,24,25/2023 bukhari shareef.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya02-7', title: 'الحديث الشريف (صحيح البخاري)', urduTitle: 'صحیح بخاری', year: 'Aalmiya 02', category: 'paper', driveLink: '/books/Paper Aalmiya  02/Solved 23,24,25/1.الحديث الشريف (صحيح البخاري).pdf', image: PAPER_IMAGE },
  { id: 'aalmiya02-8', title: 'الحديث الشريف (صحيح مسلم)', urduTitle: 'صحیح مسلم', year: 'Aalmiya 02', category: 'paper', driveLink: '/books/Paper Aalmiya  02/Solved 23,24,25/2. الحديث الشريف (صحيح مسلم).pdf', image: PAPER_IMAGE },
  { id: 'aalmiya02-9', title: 'الحديث الشريف (جامع الترمذي)', urduTitle: 'جامع الترمذی', year: 'Aalmiya 02', category: 'paper', driveLink: '/books/Paper Aalmiya  02/Solved 23,24,25/3. الحديث الشريف (جامع الترمذي).pdf', image: PAPER_IMAGE },
  { id: 'aalmiya02-10', title: 'الحديث الشريف (سنن أبي داؤد)', urduTitle: 'سنن ابی داؤد', year: 'Aalmiya 02', category: 'paper', driveLink: '/books/Paper Aalmiya  02/Solved 23,24,25/4. الحديث الشريف (سنن أبي داؤد).pdf', image: PAPER_IMAGE },
  { id: 'aalmiya02-11', title: 'الحديث الشريف (سنن النسائي، ابن ماجه)', urduTitle: 'سنن النسائی، ابن ماجہ', year: 'Aalmiya 02', category: 'paper', driveLink: '/books/Paper Aalmiya  02/Solved 23,24,25/5. الحديث الشريف (سنن النسائي، ابن ماجه).pdf', image: PAPER_IMAGE },
  { id: 'aalmiya02-12', title: '2025 Solve نحو+عربی تکلم', urduTitle: '2025 حل نحو و عربی تکلم', year: 'Aalmiya 02', category: 'paper', driveLink: '/books/Paper Aalmiya  02/Solved 23,24,25/5. حل شدہ نحو+عربی تکلم سالانہ2025.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya02-13', title: '2025 Bukhari Shareef', urduTitle: '2025 بخاری شریف', year: 'Aalmiya 02', category: 'paper', driveLink: '/books/Paper Aalmiya  02/Solved 23,24,25/بخاری شریف 2025.pdf', image: PAPER_IMAGE },
  { id: 'aalmiya02-14', title: 'بخاری شریف حل شدہ 23,24,25', urduTitle: 'بخاری شریف حل شدہ', year: 'Aalmiya 02', category: 'paper', driveLink: '/books/Paper Aalmiya  02/Solved 23,24,25/بخاری شریف حل شدہ 23,24,25(2).pdf', image: PAPER_IMAGE },
];

export function getBooksByYear(year: number): YearData | undefined {
  return allData.find(data => data.year === year);
}

export function getAllBooks(): Book[] {
  return allData.flatMap(data => [...data.books, ...data.sharahs]);
}

export function getPapersByYear(year: number): Book[] | undefined {
  return allData.find(data => data.year === year)?.papers;
}
